export const OutgoingHeaders = {
    INIT_CRYPTO: 277,
    SESSION_PARAMS: 257,
    UNIQUE_ID_MESSAGE: 439,
    AVAILABILITY_STATUS: 290,
    AUTH_OK: 3,
    USER_RIGHTS: 2,
    USER_OBJECT: 5,
    CREDIT_BALANCE: 6,
    ACTIVITY_POINT_NOTIFICATION: 438,
    INFO_FEED_ENABLE: 517,
    NAVIGATOR_SETTINGS: 455,
};
